---
version: "2"
checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 600
  method-complexity:
    config:
      threshold: 11
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 40
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 5
  similar-code:
    enabled: false
  identical-code:
    enabled: false
plugins:
  gofmt:
    # Codeclimate go fmt does not agree with tip go fmt; consider re-enabling
    # CC when the advice matches up with tip again.
    enabled: false
  govet:
    enabled: false
  golint:
    enabled: true
exclude_patterns:
  - config/
  - db/
  - dist/
  - features/
  - "**/node_modules/"
  - script/
  - "**/spec/"
  - "**/test/"
  - "**/tests/"
  - Tests/
  - "**/vendor/"
  - "**/*_test.go"
  - "**/*.d.ts"
  - .mvn/
  - "**/cicd/**"
  - "**/com/ikea/rpim/api/db/repository/**"
  - docs/