name: Project Release
on: workflow_dispatch

jobs:
  # <--------------- RUN SEMANTIC RELEASE ---------------->
  release:
    uses: erzz/workflows/.github/workflows/semantic-release.yml@main
    secrets:
      token: ${{ secrets.RELEASE_TOKEN }}
