name: Build & Scan Container Image

on:
  workflow_call:
    inputs:
      # <----------------- IMAGE OPTIONS ----------------->
      registry:
        required: false
        type: string
        description: "The domain name of the registry to push the built image to"
        default: "eu.gcr.io"
      image:
        required: true
        type: string
        description: "The path under which to create the image"
      dockerfile:
        required: false
        type: string
        description: "Relative path to the Dockerfile to build from"
        default: "Dockerfile"
      build-args:
        required: false
        type: string
        description: "Comma separated list of environment variables to pass as build args"
      # <----------------- MISC OPTIONS ------------------>
      env-file:
        required: false
        type: boolean
        description: "If there is an .env file to include set to true - expects an artifact named env-file"
        default: false
      include-tests:
        required: false
        type: boolean
        description: "Set to false in order to skip the tests and only run the build & push job"
        default: true
      # <---------------- MAVEN OPTIONS ------------------>
      mvn-settings:
        required: false
        type: boolean
        description: "If there is an maven-settings.xml file to include set to true and use mvn-settings-file to populate"
        default: false
      # <---------------- TRIVY OPTIONS ------------------>
      trivy-scan-type:
        required: false
        type: string
        description: "The comma separated list of the scan types to perform (no spaces!)"
        default: "os,library"
    secrets:
      # <------------- REGISTRY CREDENTIALS -------------->
      user:
        required: false
        description: "The username to use when authenticating with the registry"
      password:
        required: false
        description: "The password to use when authenticating with the registry"
      # <---------------- NPM CREDENTIALS ---------------->
      npm-token:
        required: false
        description: "If an NPM_TOKEN env var is required for build then add it here"
      # <--------------- MAVEN CREDENTIALS --------------->
      mvn-settings-file:
        required: false
        description: "If a maven settings file is required for build then add it here"
    outputs:
      image-name:
        description: "The full registry and path of the built image"
        value: ${{ jobs.build-image.outputs.image-name }}
      image-tag:
        description: "The image tag applied to the built image"
        value: ${{ jobs.build-image.outputs.image-tag }}
      ref-slug:
        description: "A URL sanitized version of the github ref"
        value: ${{ jobs.build-image.outputs.ref-slug }}
      short-sha:
        description: "Captures the short SHA for use in this or later workflow jobs"
        value: ${{ jobs.build-image.outputs.short-sha }}

jobs:
  # <--------------------- SOURCE-ONLY ------------------->
  build-image:
    name: Build and Push Image
    runs-on: ubuntu-latest
    outputs:
      image-name: ${{ steps.build-image.outputs.imageFullName }}
      image-tag: ${{ steps.build-image.outputs.tags }}
      short-sha: ${{ env.GITHUB_SHA_SHORT }}
      ref-slug: ${{ env.GITHUB_REF_SLUG_URL }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Slugify github variables
        uses: rlespinasse/github-slug-action@v4

      - name: Include .env file
        if: ${{ inputs.env-file }}
        uses: actions/download-artifact@v2
        with:
          name: env-file

      - name: Include maven-settings.xml
        if: ${{ inputs.mvn-settings }}
        env:
          # Hack to handle passing of strings with mixed quotes
          FILE: ${{ secrets.mvn-settings-file }}
        run: |
          echo "Creating maven-settings.xml..."
          echo "$FILE" > maven-settings.xml

      - name: Export variables
        run: |
          echo "NPM_TOKEN=${{ secrets.npm-token }}" >> $GITHUB_ENV

      - name: Build & Push Image
        id: build-image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ inputs.image }}
          registry: ${{ inputs.registry }}
          dockerfile: ${{ inputs.dockerfile }}
          username: ${{ secrets.user }}
          password: ${{ secrets.password }}
          buildArgs: ${{ inputs.build-args }}

  hadolint:
    name: Dockerfile Lint
    runs-on: ubuntu-latest
    if: ${{ inputs.include-tests }}
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Run Hadolint
        uses: hadolint/hadolint-action@v1.6.0
        with:
          format: tty
          dockerfile: ${{ inputs.dockerfile }}

  # <------------------- REQUIRES IMAGE ------------------>
  trivy:
    name: Trivy Image Scan
    runs-on: ubuntu-latest
    if: ${{ inputs.include-tests }}
    needs: build-image
    steps:
      # Checkout required for upload step's git context
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.password }}

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ needs.build-image.outputs.image-name }}:${{ needs.build-image.outputs.image-tag }}
          vuln-type: ${{ inputs.trivy-scan-type }}
          ignore-unfixed: true
          exit-code: 1
          severity: "HIGH,CRITICAL"

  dockle:
    name: Dockle Container Analysis
    runs-on: ubuntu-latest
    if: ${{ inputs.include-tests }}
    needs: build-image
    steps:
      - name: Checkout Source
        uses: actions/checkout@v2

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.password }}

      - name: Run Dockle
        uses: erzz/dockle-action@v1.1.1
        with:
          image: ${{ needs.build-image.outputs.image-name }}:${{ needs.build-image.outputs.image-tag }}
          exit-code: 1
          failure-threshold: WARN
          accept-extensions: pem,key

      - name: Upload Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Dockle Report
          path: dockle-report.json
