name: Build & Scan Container Image

on:
  workflow_call:
    inputs:
      registry:
        required: false
        type: string
        description: 'The domain name of the registry to push the built image to'
        default: 'eu.gcr.io'
      image:
        required: true
        type: string
        description: 'The path under which to create the image'
      build-args:
        required: false
        type: string
        description: 'Comma separated list of environment variables to pass as build args'
      env-file:
        required: false
        type: boolean
        description: 'If there is an .env file to include set to true - expects an artifact named env-file'
        default: false
    secrets:
      user:
        required: false
        description: 'The username to use when authenticating with the registry'
      password:
        required: false
        description: 'The password to use when authenticating with the registry'
      npm-token:
        required: false
        description: 'If an NPM_TOKEN env var is required for build then add it here'

jobs:
  build:
    name: Build and Push Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Slugify github variables
        uses: rlespinasse/github-slug-action@v3.x
      
      - name: Include .env file
        if: ${{ inputs.env-file }}
        uses: actions/download-artifact@v2
        with:
          name: env-file

      - name: Export variables
        run: |
          echo "NPM_TOKEN=${{ secrets.npm-token }}" >> $GITHUB_ENV

      - name: Build & Push Image
        id: build-image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: ${{ inputs.image }}
          registry: ${{ inputs.registry }}
          username: ${{ secrets.user }}
          password: ${{ secrets.password }}
          buildArgs: ${{ inputs.build-args }}
