name: Execute Semantic Release
on:
  workflow_call:
    inputs:
      default-config:
        required: false
        type: boolean
        description: "To use a config you have in your repository already - set to false. Otherwise uses the config in this respository."
        default: true
      dry-run:
        required: false
        type: boolean
        description: "Used to only preview the release result and notes for testing. Set to true to enable"
        default: false
      mvn-settings:
        required: false
        type: boolean
        description: "If this is a maven project, set to true and disable default-config"
        default: false
    secrets:
      token:
        required: true
        description: "A secret containing a token with relevant permissions to publish releases"
      mvn-settings-file:
        required: false
        description: "If a maven settings file is required for build then add it here"
    outputs:
      new_release_published:
        description: "Whether a new release was published (true or false)"
        value: ${{ jobs.release.outputs.new_release_published }}
      new_release_version:
        description: "Version of the new release"
        value: ${{ jobs.release.outputs.new_release_version }}
      new_release_notes:
        description: "The release notes for the new release"
        value: ${{ jobs.release.outputs.new_release_notes }}
      ref-slug:
        description: "A URL sanitized version of the github ref"
        value: ${{ jobs.release.outputs.ref-slug }}
      short-sha:
        description: "Captures the short SHA for use in this or later workflow jobs"
        value: ${{ jobs.release.outputs.short-sha }}

jobs:
  # <--------------- RUN SEMANTIC RELEASE ---------------->
  release:
    name: Semantic Release
    runs-on: ubuntu-latest
    outputs:
      new_release_published: ${{ steps.semantic-release.outputs.new_release_published }}
      new_release_version: ${{ steps.semantic-release.outputs.new_release_version }}
      new_release_notes: ${{ steps.semantic-release.outputs.new_release_notes }}
      short-sha: ${{ env.GITHUB_SHA_SHORT }}
      ref-slug: ${{ env.GITHUB_REF_SLUG_URL }}
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Slugify github variables
        uses: rlespinasse/github-slug-action@v4

      - name: Include maven-settings.xml
        if: ${{ inputs.mvn-settings }}
        env:
          # Hack to handle passing of strings with mixed quotes
          FILE: ${{ secrets.mvn-settings-file }}
        run: |
          echo "Creating maven-settings.xml..."
          echo "$FILE" > maven-settings.xml

      - name: Get Configuration
        if: ${{ inputs.default-config }}
        run: |
          echo "Fetching default configuration from erzz/workflows..."
          curl -L --fail -o .releaserc.json https://raw.githubusercontent.com/erzz/workflows/main/.github/workflows/configs/semantic-release-config.json || exit 1

      - name: Get MVN Configuration
        if: ${{ inputs.mvn-settings }}
        run: |
          echo "Fetching Maven configuration from erzz/workflows..."
          curl -L --fail -o .releaserc.json https://raw.githubusercontent.com/erzz/workflows/main/.github/workflows/configs/semantic-release-config-mvn.json || exit 1

      - name: Semantic Release
        id: semantic-release
        uses: cycjimmy/semantic-release-action@v3.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
        with:
          dry_run: ${{ inputs.dry-run }}
          extra_plugins: |
            @semantic-release/changelog
            @semantic-release/git
            conventional-changelog-conventionalcommits
            @semantic-release/exec
